TESTING = false
DEBUG = false

MAIL_SERVER = ""
MAIL_PORT = ""

MAIL_USERNAME = "519056575@qq.com"
MAIL_PASSWORD = "519056575"
MAIL_DEFAULT_SENDER = "519056575@qq.com"

SQLALCHEMY_DATABASE_URI = "mysql://allenzhang:Live20180812@127.0.0.1:3306/tenon"

[CELERY]
broker_url = "amqp://guest:guest@localhost:5672"
result_backend = "rpc://guest:guest@localhost:5672"
# event_serializer = "pickle"
# result_serializer = "pickle"
# task_serializer = "pickle"
[prometheus]
service_name = "service_tenon"
